CREATE TABLE ACTIVITY (
ID_ACTIVITY BIGINT primary key,
ACTIVITY VARCHAR(100)
);

CREATE TABLE USER (
ID_USER BIGINT AUTO_INCREMENT primary key,
USER_NAME VARCHAR(100),
PASSWORD VARCHAR(100)
);

CREATE TABLE SENSOR_TYPE (
ID_SENSOR_TYPE BIGINT primary key,
SENSOR_TYPE VARCHAR(100)
);

CREATE TABLE USER_ACTIVITY_DATA (
ID_USER_ACTIVITY_DATA BIGINT AUTO_INCREMENT primary key,
ID_ACTIVITY BIGINT, 
ID_USER BIGINT,
START_TIME TIMESTAMP,
END_TIME TIMESTAMP);


CREATE TABLE SENSOR_DATA (
ID_SENSOR_DATA BIGINT AUTO_INCREMENT primary key,
ID_USER_ACTIVITY_DATA BIGINT,
ID_SENSOR_TYPE BIGINT ,
UPDATE_TIME TIMESTAMP,
SEQUENCE BIGINT,
LATITUDE DECIMAL(10,2),
LONGITUDE DECIMAL(10,2),
AXISX DECIMAL(10,2),
AXISY DECIMAL(10,2),
AXISZ DECIMAL(10,2)
);
